---
- name: install apache
  yum:
    name: httpd
    update_cache: true
    state: present

- name: Ensure the ServerName is localhost
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerName '
    insertafter: '^#ServerName '
    line: ServerName localhost

- name: Ensure listen 8080
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: Listen 8080

- name: ensure apache is enabled and started
  service:
    name: httpd
    state: started
    enabled: true

- name: Populate service facts
  service_facts:
  register: service_facts_list

- name: insert firewalld rule for apache
  firewalld:
    port: "8080/tcp"
    permanent: true
    state: enabled
    immediate: true
  ignore_errors: true
  when: service_facts_list.ansible_facts.services["firewalld.service"].state == "running"

- name: Create site1 directory
  file:
    path: "/var/www/{{ virtual_host1 }}/public_html"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create log site1 directory
  file:
    path: "/var/www/{{ virtual_host1 }}/logs"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create site2 directory
  file:
    path: "/var/www/{{ virtual_host2 }}/public_html"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create log site2 directory
  file:
    path: "/var/www/{{ virtual_host2 }}/logs"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create images directory to site1 
  file:
    path: "/var/www/{{ virtual_host1 }}/public_html/images"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy index test page to site1
  template:
    src: templates/index.html.j2
    dest: "/var/www/{{ virtual_host1 }}/public_html/index.html"
    owner: root
    group: root
    mode: 0755
  notify: restart httpd

- name: copy index test page to site2
  copy:
    src: files/index.php
    dest: "/var/www/{{ virtual_host2 }}/public_html/index.php"
    owner: root
    group: root
    mode: 0755
  notify: restart httpd

- name: copy images
  copy:
    src: files/hello.jpg
    dest: "/var/www/{{ virtual_host1 }}/public_html/images/hello.jpg"
    owner: root
    group: root
    mode: 0755
  notify: restart httpd

- name: Create sites-avaliable directory 
  file:
    path: /etc/httpd/sites-avaliable/
    state: directory
    mode: 0755

- name: Create sites-enabled directory 
  file:
    path: /etc/httpd/sites-enabled/
    state: directory
    mode: 0755

- name: Add Include options to httpd.conf
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    insertbefore: EOF
    line: IncludeOptional sites-enabled/*.conf
  notify: restart httpd

- name: copy virtualhost1 config file
  copy:
    src: files/dev.my.site.conf
    dest: /etc/httpd/sites-avaliable/{{ virtual_host1 }}.conf
    owner: root
    group: root
    mode: 0755
  notify: restart httpd

- name: copy virtualhost2 config file
  copy:
    src: files/test.my.site.conf
    dest: /etc/httpd/sites-avaliable/{{ virtual_host2 }}.conf
    owner: root
    group: root
    mode: 0755
  notify: restart httpd

- name: Create symbolic link for site1
  file:
    src: /etc/httpd/sites-avaliable/{{ virtual_host1 }}.conf
    dest: /etc/httpd/sites-enabled/{{ virtual_host1 }}.conf
    state: link
  notify: restart httpd

- name: Create symbolic link for site2
  file:
    src: /etc/httpd/sites-avaliable/{{ virtual_host2 }}.conf
    dest: /etc/httpd/sites-enabled/{{ virtual_host2 }}.conf
    state: link
  notify: restart httpd
